name: Post commit message
on: [commit]

jobs:
  build:
    name: Post commit message
    runs-on: ubuntu-latest
    steps:
      run: echo commit successful 
      
      name: Running a multi-line script
      run: |
        echo testing multi-line action
        echo 2nd test. 