name: Post commit message
on: [push]

jobs:
  build:
    name: Post commit message
    runs-on: ubuntu-latest
    steps:
      - run: echo push successful 
      
      - name: Running a multi-line script
        run: echo testing multi-line action | echo 2nd test. 
      
      - name: Running a html file
        run: cat .\index.html